# Generated by Django 5.1.7 on 2025-03-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
