# Generated by Django 5.1.7 on 2025-03-19 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_budjet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='chat_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
