# Generated by Django 5.1.7 on 2025-03-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_budjet', '0002_customers_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='customers_images/'),
        ),
    ]
