# Generated by Django 5.1.7 on 2025-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_budjet', '0003_alter_customers_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('rejected', 'rejected'), ('accept', 'accept')], default='new', max_length=100),
        ),
    ]
