# Generated by Django 5.1.7 on 2025-03-19 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_budjet', '0005_alter_customers_options_customers_application_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customers',
            name='application_number',
            field=models.CharField(default='196ee2e9edf', max_length=11, unique=True),
        ),
    ]
