version: '3.8'

services:
  bot:
    build: .
    container_name: my_telegram_bot
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    restart: always
    env_file:
      - .env
    ports:
      - "707:8000"
    volumes:
      - .:/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
