version: '3.8'

services:
  bot:
    build: .
    container_name: my_telegram_bot
    restart: always
    env_file:
      - .env
    ports:
      - "707:707"
    volumes:
      - .:/app
    networks:
      - bot_network
    entrypoint: ["bash", "./entrypoint.sh"]

networks:
  bot_network:
    driver: bridge
