version: '3.8'

services:
  bot:
    build: .
    container_name: my_telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
